# This is a config for E2B sandbox template.
# You can use template ID (ngitzhlfdzw8jw97shwc) or template name (vibe-nextjs-zain-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-zain-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-zain-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-zain-3')

team_id = "d209330d-4593-4966-a880-844adf9c89ac"
start_cmd = "/bin/bash -lc /compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-zain-3"
template_id = "ngitzhlfdzw8jw97shwc"
